version: "3"
services:
  zentao:
    image: registry.cn-shenzhen.aliyuncs.com/a852203465/zentao:18.2
    container_name: zentao
    restart: always
    ports:
      - "8020:80"
    volumes:
      # 注意映射
      - /data/zentao:/www/zentaopms
      - /data/zentao/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - zentao_net

networks:
  zentao_net:
    external: true



















